# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18839d0703e2cdded0aeae25e32cc719d35a01cafd56b5f7aee33dd36ce74a856d040e63ea873a72d887a692f2490c2c97059d8232c491884a66ad359aac88c

test:
  secret_key_base: 1306b633e95bb287d43534e29e01fb750be2a02aa72e52473efd1d9ac7cd36e38fabc1e548d63d8e1e583c3ec0bb5434b9c571db6f447fcc41e5fa4170404b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
